services:
  postgres:
    environment:
      POSTGRES_DB: ${DB_NAME:-novacart_test}
      POSTGRES_USER: ${DB_USERNAME:-novacart_test}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set}

    ports:
      - "${DB_PORT:-5433}:5432"

    volumes:
      - postgres_test_data:/var/lib/postgresql/data

    networks:
      - novacart-test-network

volumes:
  postgres_test_data:

networks:
  novacart-test-network:
    driver: bridge
