spring:
  application:
    name: novacart

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:novacart}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${APP_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${APP_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${APP_JPA_HIBERNATE_FORMAT_SQL:true}

server:
  port: ${SERVER_PORT:8080}
